<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lab extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Lab_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('lab/lab_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Lab_model->json();
    }

    public function read($id) 
    {
        $row = $this->Lab_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_lab' => $row->id_lab,
		'nama_lab' => $row->nama_lab,
		'pjs' => $row->pjs,
	    );
            $this->load->view('lab/lab_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('lab'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('lab/create_action'),
	    'id_lab' => set_value('id_lab'),
	    'nama_lab' => set_value('nama_lab'),
	    'pjs' => set_value('pjs'),
	);
        $this->load->view('lab/lab_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_lab' => $this->input->post('nama_lab',TRUE),
		'pjs' => $this->input->post('pjs',TRUE),
	    );

            $this->Lab_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('lab'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Lab_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('lab/update_action'),
		'id_lab' => set_value('id_lab', $row->id_lab),
		'nama_lab' => set_value('nama_lab', $row->nama_lab),
		'pjs' => set_value('pjs', $row->pjs),
	    );
            $this->load->view('lab/lab_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('lab'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_lab', TRUE));
        } else {
            $data = array(
		'nama_lab' => $this->input->post('nama_lab',TRUE),
		'pjs' => $this->input->post('pjs',TRUE),
	    );

            $this->Lab_model->update($this->input->post('id_lab', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('lab'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Lab_model->get_by_id($id);

        if ($row) {
            $this->Lab_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('lab'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('lab'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_lab', 'nama lab', 'trim|required');
	$this->form_validation->set_rules('pjs', 'pjs', 'trim|required');

	$this->form_validation->set_rules('id_lab', 'id_lab', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Lab.php */
/* Location: ./application/controllers/Lab.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-29 11:03:23 */
/* http://harviacode.com */