<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mahasiswa_pc extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Mahasiswa_pc_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('mahasiswa_pc/mahasiswa_pc_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Mahasiswa_pc_model->json();
    }

    public function read($id) 
    {
        $row = $this->Mahasiswa_pc_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_mahasiswa_pc' => $row->id_mahasiswa_pc,
		'mahasiswa_pc' => $row->mahasiswa_pc,
		'penjadwalan' => $row->penjadwalan,
		'no_pc' => $row->no_pc,
	    );
            $this->load->view('mahasiswa_pc/mahasiswa_pc_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('mahasiswa_pc'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('mahasiswa_pc/create_action'),
	    'id_mahasiswa_pc' => set_value('id_mahasiswa_pc'),
	    'mahasiswa_pc' => set_value('mahasiswa_pc'),
	    'penjadwalan' => set_value('penjadwalan'),
	    'no_pc' => set_value('no_pc'),
	);
        $this->load->view('mahasiswa_pc/mahasiswa_pc_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'mahasiswa_pc' => $this->input->post('mahasiswa_pc',TRUE),
		'penjadwalan' => $this->input->post('penjadwalan',TRUE),
		'no_pc' => $this->input->post('no_pc',TRUE),
	    );

            $this->Mahasiswa_pc_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('mahasiswa_pc'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Mahasiswa_pc_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('mahasiswa_pc/update_action'),
		'id_mahasiswa_pc' => set_value('id_mahasiswa_pc', $row->id_mahasiswa_pc),
		'mahasiswa_pc' => set_value('mahasiswa_pc', $row->mahasiswa_pc),
		'penjadwalan' => set_value('penjadwalan', $row->penjadwalan),
		'no_pc' => set_value('no_pc', $row->no_pc),
	    );
            $this->load->view('mahasiswa_pc/mahasiswa_pc_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('mahasiswa_pc'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_mahasiswa_pc', TRUE));
        } else {
            $data = array(
		'mahasiswa_pc' => $this->input->post('mahasiswa_pc',TRUE),
		'penjadwalan' => $this->input->post('penjadwalan',TRUE),
		'no_pc' => $this->input->post('no_pc',TRUE),
	    );

            $this->Mahasiswa_pc_model->update($this->input->post('id_mahasiswa_pc', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('mahasiswa_pc'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Mahasiswa_pc_model->get_by_id($id);

        if ($row) {
            $this->Mahasiswa_pc_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('mahasiswa_pc'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('mahasiswa_pc'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('mahasiswa_pc', 'mahasiswa pc', 'trim|required');
	$this->form_validation->set_rules('penjadwalan', 'penjadwalan', 'trim|required');
	$this->form_validation->set_rules('no_pc', 'no pc', 'trim|required');

	$this->form_validation->set_rules('id_mahasiswa_pc', 'id_mahasiswa_pc', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Mahasiswa_pc.php */
/* Location: ./application/controllers/Mahasiswa_pc.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-29 11:03:23 */
/* http://harviacode.com */