<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Matakuliah extends CI_Controller
{
    function __construct()
    {
        parent::__construct();

        $this->load->model('Matakuliah_model');
        $this->load->library('form_validation');

        if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
        {
            redirect('/');
        }        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('matakuliah/matakuliah_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Matakuliah_model->json();
    }

    public function read($id) 
    {
        $row = $this->Matakuliah_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_matakuliah' => $row->id_matakuliah,
		'nama_matakuliah' => $row->nama_matakuliah,
	    );
            $this->load->view('matakuliah/matakuliah_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('matakuliah'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('matakuliah/create_action'),
	    'id_matakuliah' => set_value('id_matakuliah'),
	    'nama_matakuliah' => set_value('nama_matakuliah'),
	);
        $this->load->view('matakuliah/matakuliah_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_matakuliah' => $this->input->post('nama_matakuliah',TRUE),
	    );

            $this->Matakuliah_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('matakuliah'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Matakuliah_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('matakuliah/update_action'),
		'id_matakuliah' => set_value('id_matakuliah', $row->id_matakuliah),
		'nama_matakuliah' => set_value('nama_matakuliah', $row->nama_matakuliah),
	    );
            $this->load->view('matakuliah/matakuliah_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('matakuliah'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_matakuliah', TRUE));
        } else {
            $data = array(
		'nama_matakuliah' => $this->input->post('nama_matakuliah',TRUE),
	    );

            $this->Matakuliah_model->update($this->input->post('id_matakuliah', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('matakuliah'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Matakuliah_model->get_by_id($id);

        if ($row) {
            $this->Matakuliah_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('matakuliah'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('matakuliah'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_matakuliah', 'nama matakuliah', 'trim|required');

	$this->form_validation->set_rules('id_matakuliah', 'id_matakuliah', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Matakuliah.php */
/* Location: ./application/controllers/Matakuliah.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-29 11:03:23 */
/* http://harviacode.com */