<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Penjadwalan_model extends CI_Model
{

    public $table = 'penjadwalan';
    public $id = 'id_penjadwalan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_penjadwalan,nama_matakuliah,hari,jam_mulai,jam_selesai,dosen,ail,kelas');
        $this->datatables->from('penjadwalan');
        //add this line for join
        //$this->datatables->join('table2', 'penjadwalan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('penjadwalan/read/$1'),'Read')." | ".anchor(site_url('penjadwalan/update/$1'),'Update')." | ".anchor(site_url('penjadwalan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_penjadwalan');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_penjadwalan', $q);
	$this->db->or_like('nama_matakuliah', $q);
	$this->db->or_like('hari', $q);
	$this->db->or_like('jam_mulai', $q);
	$this->db->or_like('jam_selesai', $q);
	$this->db->or_like('dosen', $q);
	$this->db->or_like('ail', $q);
	$this->db->or_like('kelas', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_penjadwalan', $q);
	$this->db->or_like('nama_matakuliah', $q);
	$this->db->or_like('hari', $q);
	$this->db->or_like('jam_mulai', $q);
	$this->db->or_like('jam_selesai', $q);
	$this->db->or_like('dosen', $q);
	$this->db->or_like('ail', $q);
	$this->db->or_like('kelas', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Penjadwalan_model.php */
/* Location: ./application/models/Penjadwalan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-29 11:03:23 */
/* http://harviacode.com */